'
'  File generated by HDevelop for HALCON/DOTNET (Visual Basic .NET) Version 12.0
'
'  This file is intended to be used with the HDevelopTemplate or
'  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\vb.net

Option Strict Off

Option Explicit

Imports HalconDotNet

Module HDevelopExport测量硬币尺寸用椭圆去拟合

Public  hv_ExpDefaultWinHandle As HTuple
' Main procedure 
Private Sub action()


  ' Local iconic variables 
  Dim  ho_Th As HObject = Nothing, ho_GrayImage As HObject = Nothing
  Dim  ho_Regions As HObject = Nothing, ho_ConnectedRegions As HObject = Nothing
  Dim  ho_RegionClosing As HObject = Nothing, ho_RegionUnion1 As HObject = Nothing
  Dim  ho_RegionFillUp1 As HObject = Nothing, ho_RegionBorder As HObject = Nothing

  ' Local control variables 
  Dim  hv_Area As HTuple = New HTuple, hv_Row1 As HTuple = New HTuple
  Dim  hv_Column1 As HTuple = New HTuple, hv_Width As HTuple = New HTuple
  Dim  hv_Height As HTuple = New HTuple, hv_Row As HTuple = New HTuple
  Dim  hv_Column As HTuple = New HTuple, hv_Radius As HTuple = New HTuple
  Dim  hv_Diameter As HTuple = New HTuple

  ' Initialize local and output iconic variables 
  HOperatorSet.GenEmptyObj(ho_Th)
  HOperatorSet.GenEmptyObj(ho_GrayImage)
  HOperatorSet.GenEmptyObj(ho_Regions)
  HOperatorSet.GenEmptyObj(ho_ConnectedRegions)
  HOperatorSet.GenEmptyObj(ho_RegionClosing)
  HOperatorSet.GenEmptyObj(ho_RegionUnion1)
  HOperatorSet.GenEmptyObj(ho_RegionFillUp1)
  HOperatorSet.GenEmptyObj(ho_RegionBorder)

  'dev_close_window(...);

  ho_Th.Dispose()
  HOperatorSet.ReadImage(ho_Th, new HTuple("C:/Users/12c311/Desktop/淇彬/th.jpg"))

  ho_GrayImage.Dispose()
  HOperatorSet.Rgb1ToGray(ho_Th, ho_GrayImage)
  ho_Regions.Dispose()
  HOperatorSet.Threshold(ho_GrayImage, ho_Regions, new HTuple(0), new HTuple(210))
  ho_ConnectedRegions.Dispose()
  HOperatorSet.Connection(ho_Regions, ho_ConnectedRegions)
  ho_RegionClosing.Dispose()
  HOperatorSet.Closing(ho_ConnectedRegions, ho_ConnectedRegions, ho_RegionClosing _
      )
  ho_RegionUnion1.Dispose()
  HOperatorSet.Union1(ho_RegionClosing, ho_RegionUnion1)
  ho_RegionFillUp1.Dispose()
  HOperatorSet.FillUp(ho_RegionUnion1, ho_RegionFillUp1)



  HOperatorSet.AreaCenter(ho_RegionFillUp1, hv_Area, hv_Row1, hv_Column1)
  HOperatorSet.GetImageSize(ho_GrayImage, hv_Width, hv_Height)
  HOperatorSet.SetPart(hv_ExpDefaultWinHandle, new HTuple(0), new HTuple(0), hv_Height,  _
      hv_Width)
  ho_RegionBorder.Dispose()
  HOperatorSet.Boundary(ho_RegionFillUp1, ho_RegionBorder, new HTuple("inner"))
  HOperatorSet.SmallestCircle(ho_RegionBorder, hv_Row, hv_Column, hv_Radius)
  hv_Diameter = (new HTuple(2)).TupleMult(hv_Radius)




  ho_Th.Dispose()
  ho_GrayImage.Dispose()
  ho_Regions.Dispose()
  ho_ConnectedRegions.Dispose()
  ho_RegionClosing.Dispose()
  ho_RegionUnion1.Dispose()
  ho_RegionFillUp1.Dispose()
  ho_RegionBorder.Dispose()

End Sub



Sub InitHalcon()
  ' Default settings used in HDevelop 
  Call HOperatorSet.SetSystem(New HTuple("width"), New HTuple(512))
  Call HOperatorSet.SetSystem(New HTuple("height"), New HTuple(512))
  End Sub

  Sub RunHalcon(ByRef Window as HTuple)
    hv_ExpDefaultWinHandle = Window
    Call action
  End Sub

End Module


